language: perl
perl:
    - "5.28"
    - "5.26"
    - "5.22"
before_install:
    - cpanm --notest Devel::Cover::Report::Coveralls
install:
    - cpanm --installdeps .
after_success:
    - cover -test -report coveralls
